# Generated by Django 3.2.9 on 2022-03-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('content', models.TextField(blank=True, max_length=500, null=True, verbose_name='ürün açıklaması')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='eklenme tarihi')),
                ('active', models.BooleanField(default=True)),
                ('stock_count', models.PositiveSmallIntegerField(verbose_name='stok adedi')),
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ürün fiyatı')),
                ('slug', models.SlugField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
            ],
        ),
    ]
