# Generated by Django 3.2.9 on 2022-03-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='urunler',
        ),
    ]
